export const SkillsInformationsData = [
  {
    id: '1',
    category: 'Databases',
    description: 'Filter seekers based on their knowledge of databases.',
    data: [
      { id: '1', title: 'MySQL', value: 'mysql', type: 'skills' },
      { id: '2', title: 'PostgreSQL', value: 'postgresql', type: 'skills' },
      { id: '3', title: 'MongoDB', value: 'mongodb', type: 'skills' },
      { id: '4', title: 'SQLite', value: 'sqlite', type: 'skills' },
      { id: '5', title: 'Oracle', value: 'oracle', type: 'skills' },
      { id: '6', title: 'SQL Server', value: 'sqlserver', type: 'skills' },
      { id: '7', title: 'Redis', value: 'redis', type: 'skills' },
      { id: '8', title: 'Cassandra', value: 'cassandra', type: 'skills' },
      { id: '9', title: 'Firebase', value: 'firebase', type: 'skills' },
      {
        id: '10',
        title: 'Elasticsearch',
        value: 'elasticsearch',
        type: 'skills',
      },
      { id: '11', title: 'DynamoDB', value: 'dynamodb', type: 'skills' },
      { id: '12', title: 'Couchbase', value: 'couchbase', type: 'skills' },
      { id: '13', title: 'MariaDB', value: 'mariadb', type: 'skills' },
      { id: '14', title: 'Neo4j', value: 'neo4j', type: 'skills' },
    ],
  },
  // Programming Languages
  {
    id: '2',
    category: 'Programming Languages',
    description:
      'Filter seekers based on their knowledge of programming languages.',
    data: [
      { id: '1', title: 'JavaScript', value: 'javascript', type: 'skills' },
      { id: '2', title: 'TypeScript', value: 'typescript', type: 'skills' },
      { id: '3', title: 'C#', value: 'csharp', type: 'skills' },
      { id: '4', title: 'C++', value: 'cplusplus', type: 'skills' },
      { id: '5', title: 'C', value: 'c', type: 'skills' },
      { id: '6', title: 'Node.js', value: 'nodejs', type: 'skills' },
      { id: '7', title: 'Python', value: 'python', type: 'skills' },
      { id: '8', title: 'Java', value: 'java', type: 'skills' },
      { id: '9', title: 'Ruby', value: 'ruby', type: 'skills' },
      { id: '10', title: 'PHP', value: 'php', type: 'skills' },
      { id: '11', title: 'Go', value: 'go', type: 'skills' },
      { id: '12', title: 'Rust', value: 'rust', type: 'skills' },
      { id: '13', title: 'Perl', value: 'perl', type: 'skills' },
      { id: '14', title: 'Scala', value: 'scala', type: 'skills' },
      { id: '15', title: 'Dart', value: 'dart', type: 'skills' },
      { id: '16', title: 'R', value: 'r', type: 'skills' },
      { id: '17', title: 'Haskell', value: 'haskell', type: 'skills' },
      { id: '18', title: 'Erlang', value: 'erlang', type: 'skills' },
      { id: '19', title: 'Elixir', value: 'elixir', type: 'skills' },
      { id: '20', title: 'Assembly', value: 'assembly', type: 'skills' },
    ],
  },
  // Web Development
  {
    id: '3',
    category: 'Web Development',
    description: 'Filter seekers based on their knowledge of web development.',
    data: [
      { id: '1', title: 'HTML', value: 'html', type: 'skills' },
      { id: '2', title: 'CSS', value: 'css', type: 'skills' },
      { id: '3', title: 'React', value: 'react', type: 'skills' },
      { id: '4', title: 'Angular', value: 'angular', type: 'skills' },
      { id: '5', title: 'Vue.js', value: 'vuejs', type: 'skills' },
      { id: '6', title: 'Next.js', value: 'nextjs', type: 'skills' },
      { id: '7', title: 'Svelte', value: 'svelte', type: 'skills' },
      { id: '8', title: 'Ember.js', value: 'emberjs', type: 'skills' },
      { id: '9', title: 'Backbone.js', value: 'backbonejs', type: 'skills' },
      { id: '10', title: 'Remix', value: 'remix', type: 'skills' },
      { id: '11', title: 'Express.js', value: 'expressjs', type: 'skills' },
      { id: '12', title: 'Solid.js', value: 'solidjs', type: 'skills' },
      { id: '13', title: 'Nuxt.js', value: 'nuxtjs', type: 'skills' },
      { id: '14', title: 'Material-UI', value: 'material-ui', type: 'skills' },
      { id: '15', title: 'Django', value: 'django', type: 'skills' },
      { id: '16', title: 'Flask', value: 'flask', type: 'skills' },
      { id: '17', title: 'ASP.NET', value: 'aspnet', type: 'skills' },
      { id: '18', title: 'Spring Boot', value: 'springboot', type: 'skills' },
      { id: '19', title: 'Laravel', value: 'laravel', type: 'skills' },
      { id: '20', title: 'Bootstrap', value: 'bootstrap', type: 'skills' },
      { id: '21', title: 'Tailwind CSS', value: 'tailwindcss', type: 'skills' },
      { id: '22', title: 'SASS', value: 'sass', type: 'skills' },
      { id: '23', title: 'jQuery', value: 'jquery', type: 'skills' },
      { id: '24', title: 'WordPress', value: 'wordpress', type: 'skills' },
      { id: '25', title: 'Magento', value: 'magento', type: 'skills' },
    ],
  },
  // Cloud Platforms
  {
    id: '4',
    category: 'Cloud Platforms',
    description: 'Filter seekers based on their knowledge of cloud platforms.',
    data: [
      { id: '1', title: 'AWS', value: 'aws', type: 'skills' },
      { id: '2', title: 'Microsoft Azure', value: 'azure', type: 'skills' },
      { id: '3', title: 'Google Cloud Platform', value: 'gcp', type: 'skills' },
      { id: '4', title: 'IBM Cloud', value: 'ibmcloud', type: 'skills' },
      { id: '5', title: 'Oracle Cloud', value: 'oraclecloud', type: 'skills' },
      { id: '6', title: 'Heroku', value: 'heroku', type: 'skills' },
      { id: '7', title: 'DigitalOcean', value: 'digitalocean', type: 'skills' },
      { id: '8', title: 'Vercel', value: 'vercel', type: 'skills' },
      { id: '9', title: 'Netlify', value: 'netlify', type: 'skills' },
      { id: '10', title: 'Cloudflare', value: 'cloudflare', type: 'skills' },
    ],
  },
  // DevOps Tools
  {
    id: '5',
    category: 'DevOps Tools',
    description: 'Filter seekers based on their knowledge of DevOps tools.',
    data: [
      { id: '1', title: 'Docker', value: 'docker', type: 'skills' },
      { id: '2', title: 'Kubernetes', value: 'kubernetes', type: 'skills' },
      { id: '3', title: 'Jenkins', value: 'jenkins', type: 'skills' },
      { id: '4', title: 'Ansible', value: 'ansible', type: 'skills' },
      { id: '5', title: 'Terraform', value: 'terraform', type: 'skills' },
      { id: '6', title: 'GitLab CI/CD', value: 'gitlab-ci-cd', type: 'skills' },
      { id: '7', title: 'Travis CI', value: 'travisci', type: 'skills' },
      { id: '8', title: 'CircleCI', value: 'circleci', type: 'skills' },
      { id: '9', title: 'Puppet', value: 'puppet', type: 'skills' },
      { id: '10', title: 'Chef', value: 'chef', type: 'skills' },
      { id: '11', title: 'Nagios', value: 'nagios', type: 'skills' },
      { id: '12', title: 'Prometheus', value: 'prometheus', type: 'skills' },
      { id: '13', title: 'Grafana', value: 'grafana', type: 'skills' },
      { id: '14', title: 'Splunk', value: 'splunk', type: 'skills' },
      { id: '15', title: 'ELK Stack', value: 'elkstack', type: 'skills' },
    ],
  },
  // Data Science & Machine Learning
  {
    id: '6',
    category: 'Data Science & Machine Learning',
    description:
      'Filter seekers based on their knowledge of data science and machine learning.',
    data: [
      { id: '1', title: 'TensorFlow', value: 'tensorflow', type: 'skills' },
      { id: '2', title: 'PyTorch', value: 'pytorch', type: 'skills' },
      { id: '3', title: 'Scikit-Learn', value: 'scikit-learn', type: 'skills' },
      { id: '4', title: 'Keras', value: 'keras', type: 'skills' },
      { id: '5', title: 'Pandas', value: 'pandas', type: 'skills' },
      { id: '6', title: 'NumPy', value: 'numpy', type: 'skills' },
      { id: '7', title: 'Matplotlib', value: 'matplotlib', type: 'skills' },
      { id: '8', title: 'Seaborn', value: 'seaborn', type: 'skills' },
      { id: '9', title: 'Apache Spark', value: 'apachespark', type: 'skills' },
      { id: '10', title: 'Hadoop', value: 'hadoop', type: 'skills' },
      { id: '11', title: 'RapidMiner', value: 'rapidminer', type: 'skills' },
      { id: '12', title: 'Weka', value: 'weka', type: 'skills' },
      { id: '13', title: 'Tableau', value: 'tableau', type: 'skills' },
      { id: '14', title: 'Power BI', value: 'powerbi', type: 'skills' },
      { id: '15', title: 'SAS', value: 'sas', type: 'skills' },
      { id: '16', title: 'BigQuery', value: 'bigquery', type: 'skills' },
      { id: '17', title: 'Databricks', value: 'databricks', type: 'skills' },
    ],
  },
  // Mobile Development
  {
    id: '7',
    category: 'Mobile Development',
    description:
      'Filter seekers based on their knowledge of mobile development.',
    data: [
      { id: '1', title: 'Android', value: 'android', type: 'skills' },
      { id: '2', title: 'iOS', value: 'ios', type: 'skills' },
      { id: '3', title: 'React Native', value: 'reactnative', type: 'skills' },
      { id: '4', title: 'Flutter', value: 'flutter', type: 'skills' },
      { id: '5', title: 'Xamarin', value: 'xamarin', type: 'skills' },
      { id: '6', title: 'Swift', value: 'swift', type: 'skills' },
      { id: '7', title: 'Kotlin', value: 'kotlin', type: 'skills' },
      { id: '8', title: 'Objective-C', value: 'objective-c', type: 'skills' },
      { id: '9', title: 'Cordova', value: 'cordova', type: 'skills' },
      { id: '10', title: 'Ionic', value: 'ionic', type: 'skills' },
      { id: '11', title: 'PhoneGap', value: 'phonegap', type: 'skills' },
    ],
  },
  // Cybersecurity
  {
    id: '8',
    category: 'Cybersecurity',
    description: 'Filter seekers based on their knowledge of cybersecurity.',
    data: [
      {
        id: '1',
        title: 'Penetration Testing',
        value: 'pentesting',
        type: 'skills',
      },
      {
        id: '2',
        title: 'Ethical Hacking',
        value: 'ethicalhacking',
        type: 'skills',
      },
      {
        id: '3',
        title: 'Network Security',
        value: 'networksecurity',
        type: 'skills',
      },
      { id: '4', title: 'Cryptography', value: 'cryptography', type: 'skills' },
      {
        id: '5',
        title: 'Malware Analysis',
        value: 'malwareanalysis',
        type: 'skills',
      },
      {
        id: '6',
        title: 'Security Information and Event Management (SIEM)',
        value: 'siem',
        type: 'skills',
      },
      {
        id: '7',
        title: 'Incident Response',
        value: 'incidentresponse',
        type: 'skills',
      },
      { id: '8', title: 'Firewalls', value: 'firewalls', type: 'skills' },
      {
        id: '9',
        title: 'Intrusion Detection Systems (IDS)',
        value: 'ids',
        type: 'skills',
      },
      {
        id: '10',
        title: 'Identity and Access Management (IAM)',
        value: 'iam',
        type: 'skills',
      },
      {
        id: '11',
        title: 'Security Compliance',
        value: 'securitycompliance',
        type: 'skills',
      },
      {
        id: '12',
        title: 'Data Loss Prevention (DLP)',
        value: 'dlp',
        type: 'skills',
      },
    ],
  },
];
